/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Molmu' at '13.12.16 19:53' with Gradle 2.13
 *
 * @author Molmu, @date 13.12.16 19:53
 */
public class FizzBuzz
{
    public String getFizzOrBuzz(int i)
    {
        if (isFizzBuzz(i))
        {
            return "FizzBuzz";
        }
        if (isFizz(i))
        {
            return "Fizz";
        }
        if (isBuzz(i))
        {
            return "Buzz";
        }
        return String.valueOf(i);
    }

    private boolean isFizz(int i)
    {
        return i % 3 == 0;
    }

    private boolean isBuzz(int i)
    {
        return i % 5 == 0;
    }

    private boolean isFizzBuzz(int i)
    {
        return isFizz(i) && isBuzz(i);
    }
}
