import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import java.util.Arrays;
import java.util.List;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.Is.is;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Molmu' at '13.12.16 19:53' with Gradle 2.13
 *
 * @author Molmu, @date 13.12.16 19:53
 */
@RunWith(Parameterized.class)
public class TestFizzBuzz
{
    private FizzBuzz fizzBuzz;
    private int input;
    private String expected;

    @Parameterized.Parameters(name = "{index}: fizzBuzz[{0}]={1}")
    public static List<Object[]> data()
    {
        return Arrays.asList(new Object[][]{
                {3, "Fizz"},
                {6, "Fizz"},
                {5, "Buzz"},
                {10, "Buzz"},
                {15, "FizzBuzz"},
                {30, "FizzBuzz"},
        });
    }

    public TestFizzBuzz(int input, String expected)
    {
        this.input = input;
        this.expected = expected;
    }

    @Before
    public void setup()
    {
        fizzBuzz = new FizzBuzz();
    }

    @Test
    public void testFizzBuzz()
    {
        assertThat(fizzBuzz.getFizzOrBuzz(input), is(expected));
    }
}
